name: Issue Text

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: Thank you for creating an issue. We will normally respond within 24 hours.
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.BOT }}

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug_report.yml

      - name: Set Browser Labels
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: browsers
          block-list: |
            Other Browser
          token: ${{ secrets.GITHUB_TOKEN }}
