name: Generate PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM packages
        run: npm ci

      - name: Get translations
        run: npm run crowdin download
        env:
          api_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Build project
        run: CI=false PUBLIC_URL=https://preview.pr.blueedge.me/${{ github.event.pull_request.number }} npm run build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT }}
          publish_dir: ./build
          destination_dir: ./${{ github.event.pull_request.number }}
          cname: preview.pr.blueedge.me
          external_repository: win11bot/preview

      - name: Sleep for 60 seconds to make sure page updated
        run: sleep 60s
        shell: bash

      - name: comment Preview Ready
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            âœ”ï¸ Deploy Preview for Ready!
            ğŸ˜ Browse the preview: https://preview.pr.blueedge.me/${{ github.event.pull_request.number }} !
            ğŸ” Inspect the deploy log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                Feel free to join our github org. Click [here](https://github.com/win11react/members/issues/new?assignees=&labels=join&template=join.md&title=I+want+to+join+the+org)
          issue-number: ${{ github.event.pull_request.number }}

      - if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: âŒ Deploy Preview failed
