name: Prettier PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  prettier:
    if: "!contains(github.actor, 'win11bot')" # Skips if the bot triggered the event
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Run Commands
        run: |
          npm ci
          npm run prettier
          git config --global user.email "win11bot@win11react.com"
          git config --global user.name "win11bot"
          git add .
          git commit -m "Prettier (#${{ github.event.pull_request.number }})" -m "skip actions"
          git push
