name: released

on:
  release:
     created:

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '600s'
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          update_release_body: true
          vt_api_key: ${{ secrets.VIRUSTOTAL }}
          files: |
            .msi$
            .deb$
            .dmg$
            .zip$
